/**
 * Google Auth Provider
 * 
 * Wrapper for Google Identity Services (GIS).
 * Handles loading the GIS script, initialization with custom nonce,
 * and rendering the Sign In With Google button.
 * 
 * The custom nonce is critical for Sui zkLogin - it binds the JWT
 * to the ephemeral key pair generated by the Obsidian plugin.
 */

import { CONFIG } from '../../config';
import type { AuthProvider, CredentialCallback } from './AuthProvider';

declare global {
  interface Window {
    google?: {
      accounts: {
        id: {
          initialize: (config: GoogleIdConfig) => void;
          prompt: (callback?: (notification: PromptNotification) => void) => void;
          renderButton: (parent: HTMLElement, options: ButtonOptions) => void;
          cancel: () => void;
          disableAutoSelect: () => void;
        };
      };
    };
  }
}

interface GoogleIdConfig {
  client_id: string;
  callback: (response: GoogleCredentialResponse) => void;
  nonce?: string;
  auto_select?: boolean;
  cancel_on_tap_outside?: boolean;
  context?: 'signin' | 'signup' | 'use';
  ux_mode?: 'popup' | 'redirect';
  login_uri?: string;
  itp_support?: boolean;
  use_fedcm_for_prompt?: boolean;
}

interface ButtonOptions {
  type?: 'standard' | 'icon';
  theme?: 'outline' | 'filled_blue' | 'filled_black';
  size?: 'large' | 'medium' | 'small';
  text?: 'signin_with' | 'signup_with' | 'continue_with' | 'signin';
  shape?: 'rectangular' | 'pill' | 'circle' | 'square';
  logo_alignment?: 'left' | 'center';
  width?: string;
  locale?: string;
}

interface PromptNotification {
  isDisplayMoment: () => boolean;
  isDisplayed: () => boolean;
  isNotDisplayed: () => boolean;
  getNotDisplayedReason: () => string;
  isSkippedMoment: () => boolean;
  getSkippedReason: () => string;
  isDismissedMoment: () => boolean;
  getDismissedReason: () => string;
}

interface GoogleCredentialResponse {
  credential: string;
  select_by: string;
  clientId?: string;
}

export class GoogleAuthProvider implements AuthProvider {
  public readonly name = 'google' as const;
  
  private initialized: boolean = false;
  private scriptLoaded: boolean = false;
  private loadPromise: Promise<void> | null = null;
  private callback: CredentialCallback | null = null;

  public async loadScript(): Promise<void> {
    if (this.scriptLoaded) {
      return;
    }

    if (this.loadPromise) {
      return this.loadPromise;
    }

    this.loadPromise = new Promise((resolve, reject) => {
      if (window.google?.accounts?.id) {
        this.scriptLoaded = true;
        resolve();
        return;
      }

      const script = document.createElement('script');
      script.src = 'https://accounts.google.com/gsi/client?hl=en';
      script.async = true;
      script.defer = true;

      script.onload = () => {
        this.scriptLoaded = true;
        resolve();
      };

      script.onerror = () => {
        reject(new Error('Failed to load Google Identity Services script'));
      };

      document.head.appendChild(script);
    });

    return this.loadPromise;
  }

  public initialize(nonce: string, callback: CredentialCallback): void {
    if (!window.google?.accounts?.id) {
      throw new Error('Google Identity Services not loaded');
    }

    if (!nonce) {
      throw new Error('Nonce is required for zkLogin authentication');
    }

    this.callback = callback;

    window.google.accounts.id.initialize({
      client_id: CONFIG.googleClientId,
      callback: (response: GoogleCredentialResponse) => {
        if (this.callback && response.credential) {
          this.callback({
            credential: response.credential,
            provider: 'google',
          });
        }
      },
      nonce,
      auto_select: false,
      cancel_on_tap_outside: true,
      context: 'signin',
      ux_mode: 'popup',
      itp_support: true,
      use_fedcm_for_prompt: true,
    });

    this.initialized = true;
  }

  public renderButton(parentElement: HTMLElement): void {
    if (!this.initialized) {
      throw new Error('Google Auth Provider not initialized');
    }

    if (!window.google?.accounts?.id) {
      throw new Error('Google Identity Services not loaded');
    }

    const options: ButtonOptions = {
      type: 'standard',
      theme: 'outline',
      size: 'large',
      text: 'signin_with',
      shape: 'rectangular',
      logo_alignment: 'left',
      width: '300',
      locale: 'en',
    };

    window.google.accounts.id.renderButton(parentElement, options);
  }

  public isInitialized(): boolean {
    return this.initialized;
  }

  public reset(): void {
    this.initialized = false;
    this.callback = null;
  }

  public cancel(): void {
    if (window.google?.accounts?.id) {
      window.google.accounts.id.cancel();
    }
  }
}
