/**
 * Twitch Auth Provider
 * 
 * Implements OIDC implicit flow for Twitch authentication.
 * Uses redirect-based flow with ID token returned in URL fragment.
 * 
 * The custom nonce is critical for Sui zkLogin - it binds the JWT
 * to the ephemeral key pair generated by the Obsidian plugin.
 */

import { CONFIG } from '../../config';
import type { AuthProvider, CredentialCallback, CredentialResponse } from './AuthProvider';

const TWITCH_AUTHORIZE_URL = 'https://id.twitch.tv/oauth2/authorize';
const STORAGE_KEY_STATE = 'twitch_auth_state';
const STORAGE_KEY_NONCE = 'twitch_auth_nonce';

export class TwitchAuthProvider implements AuthProvider {
  public readonly name = 'twitch' as const;
  
  private initialized: boolean = false;
  private nonce: string | null = null;

  public async loadScript(): Promise<void> {
    // Twitch doesn't require an external script - uses standard OAuth redirect
    return Promise.resolve();
  }

  public initialize(nonce: string, callback: CredentialCallback): void {
    if (!nonce) {
      throw new Error('Nonce is required for zkLogin authentication');
    }

    if (!CONFIG.twitchClientId) {
      throw new Error('Twitch Client ID not configured');
    }

    this.nonce = nonce;
    this.initialized = true;

    // Check if we're returning from a Twitch callback
    const callbackResult = this.handleCallback();
    if (callbackResult) {
      console.log('[TwitchAuthProvider] Callback detected, invoking callback');
      callback(callbackResult);
    }
  }

  public renderButton(container: HTMLElement): void {
    if (!this.initialized) {
      throw new Error('Twitch Auth Provider not initialized');
    }

    // Create a styled Twitch login button
    const button = document.createElement('button');
    button.className = 'twitch-signin-button';
    button.innerHTML = `
      <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor" style="margin-right: 8px;">
        <path d="M11.571 4.714h1.715v5.143H11.57zm4.715 0H18v5.143h-1.714zM6 0L1.714 4.286v15.428h5.143V24l4.286-4.286h3.428L22.286 12V0zm14.571 11.143l-3.428 3.428h-3.429l-3 3v-3H6.857V1.714h13.714Z"/>
      </svg>
      Sign in with Twitch
    `;
    
    button.style.cssText = `
      display: flex;
      align-items: center;
      justify-content: center;
      width: 300px;
      height: 40px;
      background-color: #9146FF;
      color: white;
      border: none;
      border-radius: 4px;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      font-size: 14px;
      font-weight: 500;
      cursor: pointer;
      transition: background-color 0.2s;
    `;

    button.onmouseenter = () => {
      button.style.backgroundColor = '#772CE8';
    };
    button.onmouseleave = () => {
      button.style.backgroundColor = '#9146FF';
    };

    button.onclick = () => {
      this.initiateAuth();
    };

    container.innerHTML = '';
    container.appendChild(button);
  }

  public isInitialized(): boolean {
    return this.initialized;
  }

  public reset(): void {
    this.initialized = false;
    this.nonce = null;
    sessionStorage.removeItem(STORAGE_KEY_STATE);
    sessionStorage.removeItem(STORAGE_KEY_NONCE);
  }

  public cancel(): void {
    // No ongoing process to cancel for redirect flow
  }

  public initiateAuth(): void {
    if (!this.initialized || !this.nonce) {
      throw new Error('Twitch Auth Provider not initialized');
    }

    // Generate state for CSRF protection
    const state = this.generateState();
    
    // Store state and nonce for validation on callback
    sessionStorage.setItem(STORAGE_KEY_STATE, state);
    sessionStorage.setItem(STORAGE_KEY_NONCE, this.nonce);

    // Build authorization URL
    const authorizeUrl = new URL(TWITCH_AUTHORIZE_URL);
    authorizeUrl.searchParams.set('client_id', CONFIG.twitchClientId);
    authorizeUrl.searchParams.set('redirect_uri', this.getRedirectUri());
    authorizeUrl.searchParams.set('response_type', 'id_token');
    authorizeUrl.searchParams.set('scope', 'openid user:read:email');
    authorizeUrl.searchParams.set('nonce', this.nonce);
    authorizeUrl.searchParams.set('state', state);
    authorizeUrl.searchParams.set('claims', JSON.stringify({
      id_token: {
        email: null,
        email_verified: null,
      },
    }));

    console.log('[TwitchAuthProvider] Redirecting to Twitch:', authorizeUrl.toString());
    
    // Redirect to Twitch
    window.location.href = authorizeUrl.toString();
  }

  public handleCallback(): CredentialResponse | null {
    if (!this.isCallback()) {
      return null;
    }

    const hash = window.location.hash.slice(1);
    const params = new URLSearchParams(hash);

    // Check for error
    const error = params.get('error');
    if (error) {
      const errorDescription = params.get('error_description') || error;
      console.error('[TwitchAuthProvider] Auth error:', errorDescription);
      throw new Error(`Twitch authentication failed: ${errorDescription}`);
    }

    // Validate state
    const returnedState = params.get('state');
    const storedState = sessionStorage.getItem(STORAGE_KEY_STATE);
    
    if (!returnedState || returnedState !== storedState) {
      console.error('[TwitchAuthProvider] State mismatch - possible CSRF attack');
      throw new Error('Authentication failed: state mismatch');
    }

    // Extract ID token
    const idToken = params.get('id_token');
    if (!idToken) {
      console.error('[TwitchAuthProvider] No id_token in callback');
      throw new Error('Authentication failed: no ID token received');
    }

    // Clear stored state
    sessionStorage.removeItem(STORAGE_KEY_STATE);

    // Clear the hash from URL
    const cleanUrl = window.location.origin + window.location.pathname + window.location.search;
    window.history.replaceState(null, '', cleanUrl);

    console.log('[TwitchAuthProvider] Successfully extracted ID token');

    return {
      credential: idToken,
      provider: 'twitch',
    };
  }

  public isCallback(): boolean {
    const hash = window.location.hash;
    // Twitch callback contains id_token in fragment
    return hash.includes('id_token=') || hash.includes('error=');
  }

  private getRedirectUri(): string {
    // Use current origin + pathname as redirect URI
    // Remove trailing slash for consistency with Twitch redirect URI config
    const pathname = window.location.pathname.replace(/\/$/, '');
    return window.location.origin + pathname;
  }

  private generateState(): string {
    const array = new Uint8Array(32);
    crypto.getRandomValues(array);
    return Array.from(array, byte => byte.toString(16).padStart(2, '0')).join('');
  }
}
