/**
 * Google Auth Service
 * 
 * Singleton wrapper for Google Identity Services (GIS).
 * Handles loading the GIS script, initialization with custom nonce,
 * and rendering the Sign In With Google button.
 * 
 * The custom nonce is critical for Sui zkLogin - it binds the JWT
 * to the ephemeral key pair generated by the Obsidian plugin.
 */

import { CONFIG } from '../config';
import type { GoogleCredentialResponse } from '../types';

/**
 * Declares the global google namespace for TypeScript
 */
declare global {
  interface Window {
    google?: {
      accounts: {
        id: {
          initialize: (config: GoogleIdConfig) => void;
          prompt: (callback?: (notification: PromptNotification) => void) => void;
          renderButton: (parent: HTMLElement, options: ButtonOptions) => void;
          cancel: () => void;
          disableAutoSelect: () => void;
        };
      };
    };
  }
}

interface GoogleIdConfig {
  client_id: string;
  callback: (response: GoogleCredentialResponse) => void;
  nonce?: string;
  auto_select?: boolean;
  cancel_on_tap_outside?: boolean;
  context?: 'signin' | 'signup' | 'use';
  ux_mode?: 'popup' | 'redirect';
  login_uri?: string;
  itp_support?: boolean;
  use_fedcm_for_prompt?: boolean;
}

interface ButtonOptions {
  type?: 'standard' | 'icon';
  theme?: 'outline' | 'filled_blue' | 'filled_black';
  size?: 'large' | 'medium' | 'small';
  text?: 'signin_with' | 'signup_with' | 'continue_with' | 'signin';
  shape?: 'rectangular' | 'pill' | 'circle' | 'square';
  logo_alignment?: 'left' | 'center';
  width?: string;
  locale?: string;
}

interface PromptNotification {
  isDisplayMoment: () => boolean;
  isDisplayed: () => boolean;
  isNotDisplayed: () => boolean;
  getNotDisplayedReason: () => string;
  isSkippedMoment: () => boolean;
  getSkippedReason: () => string;
  isDismissedMoment: () => boolean;
  getDismissedReason: () => string;
}

/**
 * Service for handling Google Identity Services authentication
 * with support for custom nonce (required for Sui zkLogin)
 */
export class GoogleAuthService {
  private static instance: GoogleAuthService;
  private initialized: boolean = false;
  private scriptLoaded: boolean = false;
  private loadPromise: Promise<void> | null = null;

  private constructor() {}

  /**
   * Get singleton instance
   */
  public static getInstance(): GoogleAuthService {
    if (!GoogleAuthService.instance) {
      GoogleAuthService.instance = new GoogleAuthService();
    }
    return GoogleAuthService.instance;
  }

  /**
   * Load the Google Identity Services script
   */
  public async loadScript(): Promise<void> {
    if (this.scriptLoaded) {
      return;
    }

    if (this.loadPromise) {
      return this.loadPromise;
    }

    this.loadPromise = new Promise((resolve, reject) => {
      // Check if already loaded
      if (window.google?.accounts?.id) {
        this.scriptLoaded = true;
        resolve();
        return;
      }

      const script = document.createElement('script');
      script.src = 'https://accounts.google.com/gsi/client?hl=en';
      script.async = true;
      script.defer = true;

      script.onload = () => {
        this.scriptLoaded = true;
        resolve();
      };

      script.onerror = () => {
        reject(new Error('Failed to load Google Identity Services script'));
      };

      document.head.appendChild(script);
    });

    return this.loadPromise;
  }

  /**
   * Initialize Google Identity Services with custom nonce
   * 
   * @param nonce - The zkLogin nonce (hash of ephemeral public key + max epoch)
   * @param callback - Callback function to handle the credential response
   */
  public initialize(
    nonce: string,
    callback: (response: GoogleCredentialResponse) => void
  ): void {
    if (!window.google?.accounts?.id) {
      throw new Error('Google Identity Services not loaded');
    }

    if (!nonce) {
      throw new Error('Nonce is required for zkLogin authentication');
    }

    window.google.accounts.id.initialize({
      client_id: CONFIG.googleClientId,
      callback,
      nonce,  // CRITICAL: This embeds the zkLogin nonce in the JWT
      auto_select: false,
      cancel_on_tap_outside: true,
      context: 'signin',
      ux_mode: 'popup',
      itp_support: true,
      use_fedcm_for_prompt: true,
    });

    this.initialized = true;
  }

  /**
   * Render the Sign In With Google button
   * 
   * @param parentElement - DOM element to render the button into
   * @param options - Button customization options
   */
  public renderButton(
    parentElement: HTMLElement,
    options: Partial<ButtonOptions> = {}
  ): void {
    if (!this.initialized) {
      throw new Error('Google Auth Service not initialized');
    }

    if (!window.google?.accounts?.id) {
      throw new Error('Google Identity Services not loaded');
    }

    const defaultOptions: ButtonOptions = {
      type: 'standard',
      theme: 'outline',
      size: 'large',
      text: 'signin_with',
      shape: 'rectangular',
      logo_alignment: 'left',
      width: '300',
    };

    window.google.accounts.id.renderButton(parentElement, {
      ...defaultOptions,
      ...options,
    });
  }

  /**
   * Show the One Tap prompt
   * 
   * @param momentCallback - Optional callback for prompt status notifications
   */
  public prompt(momentCallback?: (notification: PromptNotification) => void): void {
    if (!this.initialized) {
      throw new Error('Google Auth Service not initialized');
    }

    if (!window.google?.accounts?.id) {
      throw new Error('Google Identity Services not loaded');
    }

    window.google.accounts.id.prompt(momentCallback);
  }

  /**
   * Cancel any ongoing prompt
   */
  public cancel(): void {
    if (window.google?.accounts?.id) {
      window.google.accounts.id.cancel();
    }
  }

  /**
   * Check if initialized
   */
  public isInitialized(): boolean {
    return this.initialized;
  }

  /**
   * Reset initialization state (for re-initialization with new nonce)
   */
  public reset(): void {
    this.initialized = false;
  }
}

export const googleAuthService = GoogleAuthService.getInstance();
